name: elisabeth
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76105
title: Over the Rainbow Events
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121009'
    - '#e1d7d7'
    - '#c3a4a8'
    - '#393637'
    - '#605a3e'
  brandStrength: 0.5181969213299453
  lightness: 0.19368494977243245
  saturation: 0.18954461463727057
  rhythmicContrast: 0.2687121327035129
purpose: []
